# Generated by Django 2.2.1 on 2019-06-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpagepicture',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutpagepicture',
            name='rsrv_char_field_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutpagepicture',
            name='rsrv_char_field_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='learningpagepicture',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='learningpagepicture',
            name='rsrv_char_field_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='learningpagepicture',
            name='rsrv_char_field_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
