# Generated by Django 2.2.1 on 2019-07-07 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20190611_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpagepicture',
            name='description2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningpagepicture',
            name='description3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningpagepicture',
            name='description4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningpagepicture',
            name='description5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningpagepicture',
            name='description6',
            field=models.TextField(blank=True, null=True),
        ),
    ]
