# Generated by Django 2.2.1 on 2019-05-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='photo_1',
            field=models.FileField(null=True, upload_to='activity_images'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='photo_2',
            field=models.FileField(null=True, upload_to='activity_images'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='photo_3',
            field=models.FileField(null=True, upload_to='activity_images'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='photo_4',
            field=models.FileField(null=True, upload_to='activity_images'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='photo_5',
            field=models.FileField(null=True, upload_to='activity_images'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='rsrv_no_field_1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='rsrv_no_field_2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='rsrv_no_field_3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='rsrv_char_field_1',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='rsrv_char_field_2',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='rsrv_char_field_3',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
