# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-05-23 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='rsrv_photo_field_1',
            field=models.FileField(null=True, upload_to='activity_images'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='rsrv_photo_field_2',
            field=models.FileField(null=True, upload_to='activity_images'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='rsrv_photo_field_3',
            field=models.FileField(null=True, upload_to='activity_images'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='rsrv_no_field_1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='rsrv_no_field_2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='rsrv_no_field_3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='rsrv_photo_field_1',
            field=models.FileField(null=True, upload_to=inventory.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='products',
            name='rsrv_photo_field_2',
            field=models.FileField(null=True, upload_to=inventory.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='products',
            name='rsrv_photo_field_3',
            field=models.FileField(null=True, upload_to=inventory.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='services',
            name='photo_1',
            field=models.FileField(null=True, upload_to='service_images'),
        ),
        migrations.AlterField(
            model_name='services',
            name='photo_2',
            field=models.FileField(null=True, upload_to='service_images'),
        ),
        migrations.AlterField(
            model_name='services',
            name='photo_3',
            field=models.FileField(null=True, upload_to='service_images'),
        ),
        migrations.AlterField(
            model_name='services',
            name='photo_4',
            field=models.FileField(null=True, upload_to='service_images'),
        ),
        migrations.AlterField(
            model_name='services',
            name='photo_5',
            field=models.FileField(null=True, upload_to='service_images'),
        ),
        migrations.AlterField(
            model_name='services',
            name='rsrv_photo_field_1',
            field=models.FileField(null=True, upload_to='service_images'),
        ),
        migrations.AlterField(
            model_name='services',
            name='rsrv_photo_field_2',
            field=models.FileField(null=True, upload_to='service_images'),
        ),
        migrations.AlterField(
            model_name='services',
            name='rsrv_photo_field_3',
            field=models.FileField(null=True, upload_to='service_images'),
        ),
    ]
