# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-05-23 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20190523_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPagePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('photo_1', models.FileField(null=True, upload_to='about_images')),
                ('photo_2', models.FileField(null=True, upload_to='about_images')),
                ('photo_3', models.FileField(null=True, upload_to='about_images')),
                ('rsrv_char_field_1', models.CharField(blank=True, max_length=80, null=True)),
                ('rsrv_char_field_2', models.CharField(blank=True, max_length=80, null=True)),
                ('rsrv_photo_field_1', models.FileField(null=True, upload_to='about_images')),
                ('rsrv_photo_field_2', models.FileField(null=True, upload_to='about_images')),
                ('rsrv_photo_field_3', models.FileField(null=True, upload_to='about_images')),
                ('active', models.NullBooleanField()),
                ('ts', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearningPagePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('photo_1', models.FileField(null=True, upload_to='learning_images')),
                ('photo_2', models.FileField(null=True, upload_to='learning_images')),
                ('photo_3', models.FileField(null=True, upload_to='learning_images')),
                ('photo_4', models.FileField(null=True, upload_to='learning_images')),
                ('photo_5', models.FileField(null=True, upload_to='learning_images')),
                ('photo_6', models.FileField(null=True, upload_to='learning_images')),
                ('rsrv_char_field_1', models.CharField(blank=True, max_length=80, null=True)),
                ('rsrv_char_field_2', models.CharField(blank=True, max_length=80, null=True)),
                ('rsrv_photo_field_1', models.FileField(null=True, upload_to='learning_images')),
                ('rsrv_photo_field_2', models.FileField(null=True, upload_to='learning_images')),
                ('rsrv_photo_field_3', models.FileField(null=True, upload_to='learning_images')),
                ('active', models.NullBooleanField()),
                ('ts', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
