# Generated by Django 2.2.1 on 2019-05-25 07:44

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20190520_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='description_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='description_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='description_5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='rsrv_photo_field_1',
            field=models.FileField(null=True, upload_to='activity_images'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='rsrv_photo_field_2',
            field=models.FileField(null=True, upload_to='activity_images'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='rsrv_photo_field_3',
            field=models.FileField(null=True, upload_to='activity_images'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='rsrv_photo_field_1',
            field=models.FileField(null=True, upload_to=inventory.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='products',
            name='rsrv_photo_field_2',
            field=models.FileField(null=True, upload_to=inventory.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='products',
            name='rsrv_photo_field_3',
            field=models.FileField(null=True, upload_to=inventory.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='services',
            name='photo_1',
            field=models.FileField(null=True, upload_to='service_images'),
        ),
        migrations.AlterField(
            model_name='services',
            name='photo_2',
            field=models.FileField(null=True, upload_to='service_images'),
        ),
        migrations.AlterField(
            model_name='services',
            name='photo_3',
            field=models.FileField(null=True, upload_to='service_images'),
        ),
        migrations.AlterField(
            model_name='services',
            name='photo_4',
            field=models.FileField(null=True, upload_to='service_images'),
        ),
        migrations.AlterField(
            model_name='services',
            name='photo_5',
            field=models.FileField(null=True, upload_to='service_images'),
        ),
        migrations.AlterField(
            model_name='services',
            name='rsrv_photo_field_1',
            field=models.FileField(null=True, upload_to='service_images'),
        ),
        migrations.AlterField(
            model_name='services',
            name='rsrv_photo_field_2',
            field=models.FileField(null=True, upload_to='service_images'),
        ),
        migrations.AlterField(
            model_name='services',
            name='rsrv_photo_field_3',
            field=models.FileField(null=True, upload_to='service_images'),
        ),
    ]
