# Generated by Django 2.2.1 on 2019-06-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20190520_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='rsrv_char_field_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='rsrv_char_field_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='rsrv_char_field_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='rsrv_char_field_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='rsrv_char_field_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='rsrv_char_field_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='rsrv_char_field_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='rsrv_char_field_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='rsrv_char_field_3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
