# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-05-24 01:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_aboutpagepicture_learningpagepicture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutPagePicture',
        ),
        migrations.DeleteModel(
            name='LearningPagePicture',
        ),
    ]
